FROM ubuntu:20.04

WORKDIR /home

RUN apt update
#instalando o servidor de e-mail base
RUN apt-get install -y systemctl postfix dnsutils iputils-ping telnet dovecot-common dovecot-core dovecot-imapd dovecot-pop3d 
#instalando o apache e o php para servir de servidor para o webmail
RUN apt-get install -y apache2 apache2-utils libapache2-mod-php php php-cli php-curl php-xml php-imap nano net-tools

RUN apt upgrade -y

#copiando as configurações

COPY main.cf /etc/postfix/main.cf

COPY /dovecot/10-mail.conf /etc/dovecot/conf.d/10-mail.conf

COPY /dovecot/20-pop3.conf /etc/dovecot/conf.d/20-pop3.conf

COPY /dovecot/10-master.conf /etc/dovecot/conf.d/10-master.conf

COPY /dovecot/dovecot.conf /etc/dovecot/dovecot.conf


COPY . .

RUN chmod +x run.sh

# Add User
RUN useradd -c 'User vinicius' -m -s /bin/false vinicius

RUN useradd -c 'User juan' -m -s /bin/false juan

# Set user password
RUN echo "vinicius:top" | chpasswd

RUN echo "juan:galado" | chpasswd

CMD ["./run.sh"]

 